Repository renatodesouza/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#7 Integrar Requisitos V1.0
  docs/requisitos.md
Labels: Analise

#6 Integrar implementação v1.0
  src/jogovelha.py
Labels: Programação

#8 Integrar arquitetura v1.0
  doc/Arquitetura.md
Labels: Arquitetura
